### PR TITLE
Issue Fixed: when terminating the program, ncurses will not always (o…

### PR DESCRIPTION
**Pull request by niroge**
…r never) close. Created the function terminate_ncurses() that gets executed when the program closes.

### CODE REVIEW

**Comment by cxd4** [comment]
Good idea.  Before I merge, is it possible to reproduce this (the ncurses program never or not always terminating) in any environment necessarily?  Does it just depend on choice of terminal emulator window (like xterm, vte, Konsole etc.)?

**Comment by niroge** [comment]
I'm not sure on what it depends, but I've always faced it: every time I close the program ncurses never ends. I've mostly used gnome-terminal, but it happens also on TTYs. I've attached a demonstration, if it can help you.

[demo.zip](https://github.com/cxd4/dhex/files/2728181/demo.zip)

**Comment by cxd4** [comment]
Interesting.  Originally I thought you meant the process was still in memory (using a task-debugging process such as `top` to check), but your video shows the program's main event loop still staying open.

I was able to reproduce the issue on both my 32- and 64-bit GNU machines but only when exiting `dhex` for the very first time after being asked about key configurations.  Subsequent executions and terminations of `dhex` seem to work normally for me.

Whatever the underlying forces at work be, your idea to register a formal termination makes sense.

**Comment by cxd4** [comment]
@niroge I lack the time to test, but did this other recently submitted patch (https://github.com/cxd4/dhex/pull/2) affect the program termination at all?  If it also serves as a fix then we might not need to register a workaround with atexit().

**Comment by niroge** [comment]
Yes, the new patch fixes the previous issue. 
[demo2.zip](https://github.com/cxd4/dhex/files/2755571/demo2.zip)

**Pull request merged**
